version: 0.1.{build}
image: Visual Studio 2017
services:
  - mssql2016
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - ps: "dir env: | where { $_.Name -ine 'APPVEYOR_RDP_PASSWORD'}"
  - ps: Get-Service | where { $_.Name -like 'MSSQL*'} | select Name
environment:
  APPVEYOR_RDP_PASSWORD:
    secure: 6RnJH3K6Be0FsXWvj3TxTQ==
  matrix:
    - platform: Any CPU
      configuration: Debug
#    - platform: Any CPU
#      configuration: Release
matrix:
  fast_finish: false
build:
  parallel: true
  verbosity: normal
before_build:
  - nuget restore
skip_commits:
  message: /NO_CI/      # Regex for matching commit message

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
