version: 0.1.{build}
image: Visual Studio 2017
init:
  - cmd: net start %SQL%
environment:
  matrix:
    - platform: Any CPU
      configuration: Debug
      SQL: MSSQL$SQL2014
    - platform: Any CPU
      configuration: Debug
      SQL: MSSQL$SQL2016
#    - platform: Any CPU
#      configuration: Release
matrix:
  fast_finish: false
build:
  parallel: true
  verbosity: normal
before_build:
  - nuget restore
