version: 0.1.{build}
image: Visual Studio 2017
init:
  - cmd: net start %SQL%
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - ps: "dir env: | where { $_.Name -ine 'APPVEYOR_RDP_PASSWORD'}"
environment:
  APPVEYOR_RDP_PASSWORD:
    secure: 6RnJH3K6Be0FsXWvj3TxTQ==
  matrix:
    - platform: Any CPU
      configuration: Debug
      SQL: MSSQL$SQL2014
    - platform: Any CPU
      configuration: Debug
      SQL: MSSQL$SQL2016
    - platform: Any CPU
      configuration: Debug
      SQL: MSSQL$SQL2017
#    - platform: Any CPU
#      configuration: Release
matrix:
  fast_finish: false
build:
  parallel: true
  verbosity: normal
before_build:
  - nuget restore
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
